apiVersion: v1
kind: Service
metadata:
  name: ngx-api
  namespace: default
  labels:
    name: ngx-api
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    app: ngx-api-dep
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: ngx-mdb-port
  - port: 80
    targetPort: 80
    protocol: TCP
    name: ngx-bdb-api-port
  type: LoadBalancer
