###############################################################
# This config file runs nginx as a k8s deployment and exposes #
# it using an external load balancer.                         #
# This deployment is used as a front end to both BigchainDB   #
# and MongoDB.                                                #
###############################################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ngx-ws-instance-0-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ngx-ws-instance-0-dep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: bigchaindb/nginx_ws:1.0
        imagePullPolicy: Always
        env:
        - name: BIGCHAINDB_BACKEND_HOST
          value: bdb-instance-0.default.svc.cluster.local
        - name: BIGCHAINDB_WS_FRONTEND_PORT
          value: "81"
        - name: BIGCHAINDB_WS_BACKEND_PORT
          value: "9985"
        - name: DNS_SERVER
          value: "10.0.0.10"
        ports:
        - containerPort: 81
          hostPort: 81
          name: public-ws-port
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
      restartPolicy: Always
